import type { CommandPaletteContent } from "@/command-palette/types";

export const commandPaletteContent = {
  title: "Command Palette",
  inputLabel: "Search commands",
  resultsLabel: "Command results",
  closeLabel: "Close command palette",
  placeholder: "Search projects, notes, commands...",
  shortcutHint: {
    mac: "{modifier} K",
    default: "{modifier} K",
  },
  emptyLabel: "Suggestions",
  noResultsTitle: "No matching commands found.",
  noResultsDescription: "Try one of the common starting points below.",
  noResultsSuggestionLabel: "Suggestions",
  noResultsSuggestionCommandIds: [
    "action-download-resume",
    "nav-projects",
    "nav-notes",
    "external-github",
    "external-linkedin",
  ],
  mobileTriggerLabel: "Command",
  firstVisitHintTemplate: "Press {shortcut} to explore the portfolio",
  personalization: {
    pinnedLabel: "Pinned",
    pinnedEmptyLabel: "No pinned commands yet.",
    recentLabel: "Recent",
    recentEmptyLabel: "No recent commands yet.",
    mostUsedLabel: "Most Used",
    mostUsedEmptyLabel: "No usage history yet.",
    onboardingLabel: "Suggestions",
    favoriteLabel: "Pin command",
    unfavoriteLabel: "Unpin command",
    favoriteLimitMessage: "You can pin up to 5 commands.",
  },
  footerShortcuts: [
    { id: "navigate", keys: "↑↓", label: "Navigate" },
    { id: "open", keys: "↵", label: "Open" },
    { id: "close", keys: "Esc", label: "Close" },
    { id: "toggle", keys: "{modifier} K", label: "Toggle" },
  ],
  categories: [
    { id: "navigation", label: "Navigation" },
    { id: "project", label: "Projects" },
    { id: "skill", label: "Skills" },
    { id: "note", label: "Notes" },
    { id: "journey", label: "Journey" },
    { id: "action", label: "Actions" },
    { id: "external", label: "External Links" },
    { id: "future-ai", label: "Future AI Commands" },
  ],
  suggestionGroups: [
    {
      id: "recent",
      label: "Recent",
      commandIds: [
        "project-medrouter",
        "action-download-resume",
        "external-linkedin",
      ],
    },
    {
      id: "quick-actions",
      label: "Quick Actions",
      commandIds: ["action-email", "external-github"],
    },
    {
      id: "navigation",
      label: "Navigation",
      commandIds: [
        "nav-about",
        "nav-projects",
        "nav-notes",
        "nav-journey",
        "nav-contact",
      ],
    },
  ],
} satisfies CommandPaletteContent;
