import { contactContent } from "@/content/contact";
import { projectsContent } from "@/content/projects";
import type { CommandPaletteContent } from "@/command-palette/types";

const contactLinks = new Map(
  contactContent.links.map((link) => [link.id, link] as const),
);

const email = contactLinks.get("email");
const github = contactLinks.get("github");
const linkedin = contactLinks.get("linkedin");
const resume = contactLinks.get("resume");
const medrouter = projectsContent.projects.find(
  (project) => project.slug === "medrouter",
);

export const commandPaletteContent = {
  title: "Command Palette",
  inputLabel: "Search commands",
  resultsLabel: "Command results",
  closeLabel: "Close command palette",
  placeholder: "Search projects, notes, commands...",
  shortcutHint: {
    mac: "⌘K",
    default: "Ctrl+K",
  },
  emptyLabel: "Suggestions",
  noResultsTitle: "No commands found.",
  noResultsDescription: "Try a navigation item, project name, or quick action.",
  mobileTriggerLabel: "Command",
  footerShortcuts: [
    { id: "navigate", keys: "↑↓", label: "Navigate" },
    { id: "open", keys: "↵", label: "Open" },
    { id: "close", keys: "Esc", label: "Close" },
    { id: "toggle", keys: "⌘K", label: "Toggle" },
  ],
  categories: [
    { id: "navigation", label: "Navigation" },
    { id: "project", label: "Project" },
    { id: "action", label: "Actions" },
    { id: "external", label: "External" },
    { id: "theme", label: "Theme" },
  ],
  suggestionGroups: [
    {
      id: "recent",
      label: "Recent",
      commandIds: ["project-medrouter", "download-resume", "open-linkedin"],
    },
    {
      id: "quick-actions",
      label: "Quick Actions",
      commandIds: ["email", "open-github"],
    },
    {
      id: "navigation",
      label: "Navigation",
      commandIds: [
        "nav-about",
        "nav-projects",
        "nav-notes",
        "nav-journey",
        "nav-contact",
      ],
    },
  ],
  commands: [
    {
      id: "nav-home",
      title: "Home",
      description: "Return to the opening section",
      category: "navigation",
      action: { type: "scroll", targetId: "hero" },
      keywords: ["home", "top", "start", "intro", "opening"],
      aliases: ["home", "top", "start"],
      indicator: "↵",
    },
    {
      id: "nav-about",
      title: "About",
      description: "Learn more about me",
      category: "navigation",
      action: { type: "scroll", targetId: "about" },
      keywords: ["about", "profile", "person", "intro"],
      aliases: ["about", "profile", "intro"],
      indicator: "↵",
    },
    {
      id: "nav-mission",
      title: "Mission",
      description: "Read the current engineering mission",
      category: "navigation",
      action: { type: "scroll", targetId: "current-mission" },
      keywords: ["mission", "current mission", "problem"],
      aliases: ["mission", "problem", "current mission"],
      indicator: "↵",
    },
    {
      id: "nav-thinking",
      title: "Thinking",
      description: "Explore engineering principles",
      category: "navigation",
      action: { type: "scroll", targetId: "engineering-principles" },
      keywords: ["thinking", "principles", "how i think", "engineering"],
      aliases: ["thinking", "principles", "how i think"],
      indicator: "↵",
    },
    {
      id: "nav-projects",
      title: "Projects",
      description: "Browse engineering projects",
      category: "navigation",
      action: { type: "scroll", targetId: "projects" },
      keywords: ["projects", "work", "featured projects"],
      aliases: ["projects", "work", "portfolio"],
      indicator: "↵",
    },
    {
      id: "nav-skills",
      title: "Skills",
      description: "Technical stack",
      category: "navigation",
      action: { type: "scroll", targetId: "skills" },
      keywords: ["skills", "toolkit", "tools", "stack"],
      aliases: ["skills", "toolkit", "stack"],
      indicator: "↵",
    },
    {
      id: "nav-notes",
      title: "Notes",
      description: "Engineering notebook",
      category: "navigation",
      action: { type: "scroll", targetId: "journal" },
      keywords: ["notes", "journal", "writing", "learning"],
      aliases: ["notes", "journal", "notebook"],
      indicator: "↵",
    },
    {
      id: "nav-journey",
      title: "Journey",
      description: "Career timeline",
      category: "navigation",
      action: { type: "scroll", targetId: "journey" },
      keywords: ["journey", "timeline", "path"],
      aliases: ["journey", "timeline", "path"],
      indicator: "↵",
    },
    {
      id: "nav-contact",
      title: "Contact",
      description: "Ways to reach me",
      category: "navigation",
      action: { type: "scroll", targetId: "contact" },
      keywords: ["contact", "reach", "connect"],
      aliases: ["contact", "reach", "connect"],
      indicator: "↵",
    },
    {
      id: "project-medrouter",
      title: medrouter?.title ?? "MEDROUTER",
      description: "Featured healthcare AI project",
      category: "project",
      action: { type: "scroll", targetId: "featured-project" },
      keywords: ["medrouter", "medical ai", "routing", "case study"],
      aliases: ["medrouter", "medical ai", "routing"],
      indicator: "↵",
    },
    {
      id: "project-bhagavadgeetha",
      title: "BhagavadGeetha.io",
      description: "Future project case study",
      category: "project",
      action: { type: "disabled" },
      keywords: ["bhagavadgeetha", "bhagavadgeetha.io", "geetha"],
      aliases: ["bhagavadgeetha", "geetha", "reading"],
      indicator: "Soon",
      disabled: true,
      disabledReason: "Placeholder",
    },
    {
      id: "project-nova",
      title: "NOVA",
      description: "Future agentic systems case study",
      category: "project",
      action: { type: "disabled" },
      keywords: ["nova", "assistant", "agent"],
      aliases: ["nova", "assistant", "agent"],
      indicator: "Soon",
      disabled: true,
      disabledReason: "Placeholder",
    },
    {
      id: "download-resume",
      title: "Download Resume",
      description: "Download latest PDF resume",
      category: "action",
      action: {
        type: "download",
        href: resume?.href ?? "/resume.pdf",
        filename: "Sree-Manas-Resume.pdf",
      },
      keywords: ["resume", "cv", "download resume", "download cv"],
      aliases: ["resume", "cv", "download cv"],
      indicator: "↓",
    },
    {
      id: "email",
      title: "Email",
      description: "Compose a new email",
      category: "action",
      action: { type: "mailto", href: email?.href ?? "mailto:sree.manas@example.com" },
      keywords: ["mail", "email", "contact", "hire", "send mail"],
      aliases: ["email", "mail", "hire", "send mail"],
      indicator: "✉",
    },
    {
      id: "open-github",
      title: "GitHub",
      description: "Open source repositories",
      category: "external",
      action: { type: "open", href: github?.href ?? "https://github.com/SreeManas" },
      keywords: ["github", "git", "repo", "repositories", "source"],
      aliases: ["github", "repo", "git", "source"],
      indicator: "↗",
    },
    {
      id: "open-linkedin",
      title: "LinkedIn",
      description: "Professional profile",
      category: "external",
      action: { type: "open", href: linkedin?.href ?? "https://www.linkedin.com/" },
      keywords: ["linkedin", "li", "linkedin profile"],
      aliases: ["linkedin", "li", "profile"],
      indicator: "↗",
    },
    {
      id: "copy-email",
      title: "Copy Email",
      description: "Copy email address",
      category: "action",
      action: {
        type: "copy",
        value: (email?.href ?? "mailto:sree.manas@example.com").replace(
          /^mailto:/,
          "",
        ),
        successMessage: "Email copied.",
      },
      keywords: ["copy email", "email copy", "mail"],
      aliases: ["copy email", "email", "mail"],
      indicator: "⧉",
    },
    {
      id: "copy-github",
      title: "Copy GitHub",
      description: "Copy GitHub profile URL",
      category: "action",
      action: {
        type: "copy",
        value: github?.href ?? "https://github.com/SreeManas",
        successMessage: "GitHub copied.",
      },
      keywords: ["copy github", "github copy", "copy git"],
      aliases: ["copy github", "github", "git"],
      indicator: "⧉",
    },
    {
      id: "copy-linkedin",
      title: "Copy LinkedIn",
      description: "Copy LinkedIn profile URL",
      category: "action",
      action: {
        type: "copy",
        value: linkedin?.href ?? "https://www.linkedin.com/",
        successMessage: "LinkedIn copied.",
      },
      keywords: ["copy linkedin", "linkedin copy", "copy li"],
      aliases: ["copy linkedin", "linkedin", "li"],
      indicator: "⧉",
    },
    {
      id: "theme-placeholder",
      title: "Theme Switching",
      description: "Theme architecture placeholder",
      category: "theme",
      action: { type: "disabled" },
      keywords: ["theme", "dark", "light", "toggle theme"],
      aliases: ["theme", "dark", "light"],
      indicator: "Soon",
      disabled: true,
      disabledReason: "Not available yet",
    },
  ],
} satisfies CommandPaletteContent;
